### ISSUE TITLE
Add hololive English generation 4 -Justice-

### ISSUE THREAD

**Issue by satsuki-sama** [PoiScript/HoloStats#869]
A new generation of hololive English has debuted, named Justice, featuring four members.

```yaml
vtuber_id: elizabeth-rose-bloodflame
native_name: Elizabeth Rose Bloodflame
japanese_name: エリザベス・ローズ・ブラッドフレイム
english_name:  
youtube_channel_id: UCW5uhrG1eCBYditmhL0Ykjw
twitch_channel_id: 
twitter_id: ERBloodflame
```

```yaml
vtuber_id: gigi-murin
native_name: Gigi Murin
japanese_name: ジジ・ムリン
english_name:  
youtube_channel_id: UCDHABijvPBnJm7F-KlNME3w
twitch_channel_id: 
twitter_id: gigimurin
```

```yaml
vtuber_id: cecilia-immergreen
native_name: Cecilia Immergreen
japanese_name: セシリア・イマーグリーン
english_name:  
youtube_channel_id: UCvN5h1ShZtc7nly3pezRayg
twitch_channel_id: 
twitter_id: ceciliaimgreen
```

```yaml
vtuber_id: raora-panthera
native_name: Raora Panthera
japanese_name: ラオーラ・パンテーラ 
english_name:  
youtube_channel_id: UCl69AEx4MdqMZH7Jtsm7Tig
twitch_channel_id: 
twitter_id: raorapanthera
```

```yaml
group_id: justice
root: false # subset of hololive English
native_name: Hololive English -Justice-
japanese_name: ホロライブEnglish -Justice-
english_name:
children: ["vtuber:elizabeth-rose-bloodflame", "vtuber:gigi-murin", "vtuber:cecilia-immergreen", "vtuber:raora-panthera"]
```
