### ISSUE TITLE
Add VSPO! English first wave, and separate VSPO! into 2 smaller subsets

### ISSUE THREAD

**Issue by LiquidRekto** [PoiScript/HoloStats#872]
```yaml
vtuber_id: arya-kuroha
native_name: Arya Kuroha
japanese_name: 黒刃 アリヤ
english_name:
youtube_channel_id: UCLlJpxXt6L5d-XQ0cDdIyDQ
twitch_channel_id:
twitter_id: aryakuroha
```
```yaml
vtuber_id: jira-jisaki
native_name: Jira Jisaki
japanese_name: 地崎 ジラ
english_name:
youtube_channel_id: UCeCWj-SiJG9SWN6wGORiLmw
twitch_channel_id:
twitter_id: jirajisaki
```
```yaml
vtuber_id: remia-aotsuki
native_name: Remia Aotsuki
japanese_name: 青月 レミア
english_name:
youtube_channel_id: UCCra1t-eIlO3ULyXQQMD9Xw
twitch_channel_id:
twitter_id: RemiaAotsuki
```
```yaml
vtuber_id: vspo-en-official
native_name: VSPO! EN
japanese_name: VSPO! EN公式
english_name:
youtube_channel_id: UC7nyueGsb-5VDNPRh6pHtCA
twitch_channel_id:
twitter_id: VSPO_EN
```

```yaml
group_id: vspo-en
root: false  # subset of VSPO!
native_name: VSPO! EN
japanese_name: ぶいすぽっ！ EN
english_name:
children: ["vtuber:vspo-en-official", "vtuber:arya-kuroha", "vtuber:jira-jisaki", "vtuber:remia-aotsuki"]
```

The current talents in the big group `vspo` should be moved to newly created group `vspo-jp`

```yaml
group_id: vspo-jp
root: false # subset of VSPO!
native_name: ぶいすぽっ！
japanese_name:
english_name: VSPO! JP
children: ["vtuber:vspo-official", "vtuber:yumeno-akari","vtuber:yakumo-beni","vtuber:tosaki-mimi","vtuber:tachibana-hinano","vtuber:shiranami-ramune","vtuber:shinomiya-runa","vtuber:nekota-tsuna","vtuber:kurumi-noah","vtuber:komori-met","vtuber:kogara-toto","vtuber:kisaragi-ren","vtuber:kaminari-qpi","vtuber:kaga-sumire","vtuber:kaga-nazuna","vtuber:ichinose-uruha","vtuber:hanabusa-lisa","vtuber:asumi-sena","vtuber:aizawa-ema"]
```
