### ISSUE TITLE
Add other vtuber

### ISSUE THREAD

**Issue by cjmaxik** [PoiScript/HoloStats#874]
```yaml
# template of adding new vtuber
vtuber_id: pillowdear #required, unique id, must be kebab-case
native_name: PillowDear # required, name in their naive language
japanese_name: # optional, name in Japanese, leave it blank if equals to `native_name`
english_name: # optional, name in English, leave it blank if equals to `native_name`
youtube_channel_id: UCSPiaTLJ5FQj7BJAM6Y4j7w # required, youtube channel id
twitch_channel_id: pillowdearasmr # optional, twitch channel id
twitter_id: pillowdearASMR # optional, twitter username
```
