### ISSUE TITLE
Add new VSPO! JP and VSPO! EN members

### ISSUE THREAD

**Issue by janzd** [PoiScript/HoloStats#875]
Three VSPO! JP members that have debuted in the past year and haven't been added yet.

```yaml
# template of adding new vtuber
vtuber_id: yano-kuromu
native_name: 夜乃くろむ
japanese_name: Yano Kuromu
english_name:
youtube_channel_id: UCX4WL24YEOUYd7qDsFSLDOw
twitch_channel_id:
twitter_id: kuromu_yano
```

```yaml
# template of adding new vtuber
vtuber_id: tsumugi-kokage
native_name: 紡木こかげ
japanese_name: Tsumugi Kokage
english_name:
youtube_channel_id: UC-WX1CXssCtCtc2TNIRnJzg
twitch_channel_id:
twitter_id: kokage_tsumugi
```

```yaml
# template of adding new vtuber
vtuber_id: sendo-yuuhi
native_name: 千燈ゆうひ
japanese_name: Sendo Yuuhi
english_name:
youtube_channel_id: UCuDY3ibSP2MFRgf7eo3cojg
twitch_channel_id: sendo_yuuhi
twitter_id: yuuhi_sendo
```

Two VSPO! EN members that debuted in August.

```yaml
# template of adding new vtuber
vtuber_id: riko-solari
native_name: Riko Solari
japanese_name:
english_name:
youtube_channel_id: UC7Xglp1fske9zmRe7Oj8YyA
twitch_channel_id:
twitter_id: rikosolari
```

```yaml
# template of adding new vtuber
vtuber_id: narin-mikure
native_name: Narin Mikure
japanese_name:
english_name:
youtube_channel_id: UCKSpM183c85d5V2cW5qaUjA
twitch_channel_id:
twitter_id: narinmikure
```
