### ISSUE TITLE
hololive DEV_IS FLOW GLOW

### ISSUE THREAD

**Issue by gcobc12632** [PoiScript/HoloStats#876]
These new members are part of the new group FLOW GLOW under hololive DEV_IS, so I'm not sure how to add a new branch.

```yaml
# template of adding new vtuber
vtuber_id: isaki-riona #required, unique id, must be kebab-case
native_name: 響咲リオナ # required, name in their naive language
japanese_name: # optional, name in Japanese, leave it blank if equals to `native_name`
english_name: Isaki Riona # optional, name in English, leave it blank if equals to `native_name`
youtube_channel_id: UC9LSiN9hXI55svYEBrrK-tw # required, youtube channel id
twitch_channel_id: # optional, twitch channel id
twitter_id: isakiriona # optional, twitter username
```
```yaml
# template of adding new vtuber
vtuber_id: koganei-niko #required, unique id, must be kebab-case
native_name: 虎金妃笑虎 # required, name in their naive language
japanese_name: # optional, name in Japanese, leave it blank if equals to `native_name`
english_name: Koganei Niko # optional, name in English, leave it blank if equals to `native_name`
youtube_channel_id: UC9LSiN9hXI55svYEBrrK-tw # required, youtube channel id
twitch_channel_id: # optional, twitch channel id
twitter_id: isakiriona # optional, twitter username
```
```yaml
# template of adding new vtuber
vtuber_id: mizumiya-su #required, unique id, must be kebab-case
native_name: 水宮枢 # required, name in their naive language
japanese_name: # optional, name in Japanese, leave it blank if equals to `native_name`
english_name: Mizumiya Su # optional, name in English, leave it blank if equals to `native_name`
youtube_channel_id: UCjk2nKmHzgH5Xy-C5qYRd5A # required, youtube channel id
twitch_channel_id: # optional, twitch channel id
twitter_id: mizumiya_su # optional, twitter username
```
```yaml
# template of adding new vtuber
vtuber_id: rindo-chihaya #required, unique id, must be kebab-case
native_name: 輪堂千速 # required, name in their naive language
japanese_name: # optional, name in Japanese, leave it blank if equals to `native_name`
english_name: Rindo Chihaya # optional, name in English, leave it blank if equals to `native_name`
youtube_channel_id: UCKMWFR6lAstLa7Vbf5dH7ig # required, youtube channel id
twitch_channel_id: # optional, twitch channel id
twitter_id: rindochihaya # optional, twitter username
```
```yaml
# template of adding new vtuber
vtuber_id: kikirara-vivi #required, unique id, must be kebab-case
native_name: 綺々羅々ヴィヴィ # required, name in their naive language
japanese_name: # optional, name in Japanese, leave it blank if equals to `native_name`
english_name: Kikirara Vivi # optional, name in English, leave it blank if equals to `native_name`
youtube_channel_id: UCGzTVXqMQHa4AgJVJIVvtDQ # required, youtube channel id
twitch_channel_id: # optional, twitch channel id
twitter_id: kikiraravivi # optional, twitter username
```
